package:
  name: example_cpp_cookiecutter
  version: 0.1.0

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - cmake>=3.1
    - conda-forge::xtl
    - conda-forge::xtensor
    - python>=3.6
    - numpy>=1.16
    - conda-forge::pybind11
    - conda-forge::xtensor-python
    
  run:
    - numpy>=1.16
    - python>=3.6
    
test:
  requires:
    - pytest
  imports:
    - example_cpp_cookiecutter
  
  commands:
    - test -d ${PREFIX}/include/example_cpp_cookiecutter           # [unix]
    - test -f ${PREFIX}/include/example_cpp_cookiecutter/example_cpp_cookiecutter.hpp # [unix]
    - if exist %LIBRARY_PREFIX%\include\example_cpp_cookiecutter\example_cpp_cookiecutter.hpp (exit 0) else (exit 1)  # [win]
    # - make cpp-test
    # -  make python-test

about:
  home:  https://github.com/JohnDoe/example_cpp_cookiecutter
  
  summary: 'example_cpp_cookiecutter is a modern C++ library'
  description: 'example_cpp_cookiecutter is a modern C++ library'
  documentation_url: https://readthedocs.org/projects/example_cpp_cookiecutter/
  dev_url: https://github.com/JohnDoe/example_cpp_cookiecutter

extra:
  recipe-maintainers:
    - FAKE NAME

