#pragma once
#ifndef EXAMPLE_CPP_COOKIECUTTER_EXAMPLE_CPP_COOKIECUTTER_VERSION_MAJOR_HPP
#define EXAMPLE_CPP_COOKIECUTTER_EXAMPLE_CPP_COOKIECUTTER_VERSION_MAJOR_HPP



#define EXAMPLE_CPP_COOKIECUTTER_VERSION_MAJOR 0


namespace example_cpp_cookiecutter {


} // end namespace example_cpp_cookiecutter


#endif // EXAMPLE_CPP_COOKIECUTTER_EXAMPLE_CPP_COOKIECUTTER_VERSION_MAJOR_HPP